packages:
  - packages/*
  - apps/*

catalog:
  '@hono/node-server': ^1.19.9
  '@types/bcryptjs': ^3.0.0
  '@types/node': ^20.19.37
  '@types/pg': ^8.16.0
  bcryptjs: ^3.0.3
  hono: ^4.11.9
  pg: ^8.18.0
  postgres: ^3.4.8
  tsx: ^4.7.1
  typescript: ^5.8.3
  zod: ^4.3.6
