create extension if not exists pg_stat_statements;

create table agencies (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create table users (
    id bigint generated by default as identity primary key,
    agency_id bigint not null references agencies(id) on delete cascade,
    email text not null unique,
    password_hash text not null,
    name text,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create table events (
    id bigint generated by default as identity primary key,
    agency_id bigint not null references agencies(id) on delete cascade,
    name text,
    artist text,
    date timestamptz,
    description text,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create index on users(agency_id);
create index on events(agency_id);

alter table users enable row level security;
alter table events enable row level security;

create policy agency_isolation on users
    using (agency_id = current_setting('app.current_agency_id', true)::bigint);

create policy agency_isolation on events
    using (agency_id = current_setting('app.current_agency_id', true)::bigint);

create role postgrest_anon nologin;
grant usage on schema public to postgrest_anon;

create role agency_group;

create role agency_pg         login password 'XXXXXXXXXXXXXXXXXXXXXXX' connection limit 20 in role agency_group;
create role "agency_pg-pool"    login password 'XXXXXXXXXXXXXXXXXXXXXXX' connection limit 20 in role agency_group;
create role agency_pgbouncer  login password 'XXXXXXXXXXXXXXXXXXXXXXX' connection limit 20 in role agency_group;
create role agency_postgrest  login password 'XXXXXXXXXXXXXXXXXXXXXXX' connection limit 22 in role agency_group;
create role agency_hyperdrive login password 'XXXXXXXXXXXXXXXXXXXXXXX' connection limit 20 in role agency_group;
create role agency_node       login password 'XXXXXXXXXXXXXXXXXXXXXXX' connection limit 20 in role agency_group;

grant select, insert, update, delete on users to agency_group;
grant select, insert, update, delete on events to agency_group;
grant select on agencies to agency_group;

create or replace function set_agency_context_by_slug_fn(p_agency_slug text)
returns bigint as $$
declare
    v_agency_id bigint;
begin
    select id into v_agency_id
    from agencies
    where slug = p_agency_slug;
    if v_agency_id is null then
        raise exception 'invalid_agency';
    end if;
    perform set_config('app.current_agency_id', v_agency_id::text, true);
    return v_agency_id;
end;
$$ language plpgsql;

create or replace function create_user_fn(
    p_email text,
    p_password_hash text,
    p_agency_slug text
)
returns table(id bigint, email text, agency_id bigint, name text) as $$
declare
    v_agency_id bigint;
begin
    select set_agency_context_by_slug_fn(p_agency_slug) into v_agency_id;
    return query
    insert into users (email, password_hash, agency_id)
    values (p_email, p_password_hash, v_agency_id)
    returning users.id, users.email, users.agency_id, users.name;
end;
$$ language plpgsql;

create or replace function signin_fn(
    p_email text,
    p_agency_slug text
)
returns table(
    id bigint,
    password_hash text,
    agency_id bigint,
    agency_slug text
) as $$
declare
    v_agency_id bigint;
begin
    select set_agency_context_by_slug_fn(p_agency_slug) into v_agency_id;
    return query
    select u.id, u.password_hash, u.agency_id, p_agency_slug
    from users u
    where u.email = p_email;
end;
$$ language plpgsql;

create or replace function set_agency_context_by_id_fn(p_agency_id bigint)
returns void as $$
begin
    perform set_config('app.current_agency_id', p_agency_id::text, true);
end;
$$ language plpgsql;

create or replace function get_agency_users_fn(p_agency_id bigint)
returns table(
    id bigint, email text, agency_id bigint, name text
) as $$
begin
    perform set_agency_context_by_id_fn(p_agency_id);
    return query
    select u.id, u.email, u.agency_id, u.name
    from users u;
end;
$$ language plpgsql;

create or replace function create_event_fn(
    p_agency_id bigint,
    p_name text,
    p_artist text,
    p_date timestamptz,
    p_description text
)
returns table(id bigint, agency_id bigint, name text, artist text, date timestamptz, description text) as $$
begin
    perform set_agency_context_by_id_fn(p_agency_id);
    return query
    insert into events (agency_id, name, artist, date, description)
    values (p_agency_id, p_name, p_artist, p_date, p_description)
    returning events.id, events.agency_id, events.name, events.artist, events.date, events.description;
end;
$$ language plpgsql;

create or replace function get_agency_events_fn(p_agency_id bigint)
returns table(id bigint, agency_id bigint, name text, artist text, date timestamptz, description text) as $$
begin
    perform set_agency_context_by_id_fn(p_agency_id);
    return query
    select e.id, e.agency_id, e.name, e.artist, e.date, e.description
    from events e;
end;
$$ language plpgsql;

grant execute on function signin_fn(text, text) to postgrest_anon;
grant execute on function create_user_fn(text, text, text) to postgrest_anon;
grant execute on function set_agency_context_by_slug_fn(text) to postgrest_anon;
alter function signin_fn(text, text) security definer;
alter function create_user_fn(text, text, text) security definer;
alter function set_agency_context_by_slug_fn(text) security definer;

grant execute on function set_agency_context_by_slug_fn(text) to agency_group;
grant execute on function create_user_fn(text, text, text) to agency_group;
grant execute on function signin_fn(text, text) to agency_group;
grant execute on function set_agency_context_by_id_fn(bigint) to agency_group;
grant execute on function get_agency_users_fn(bigint) to agency_group;
grant execute on function create_event_fn(bigint, text, text, timestamptz, text) to agency_group;
grant execute on function get_agency_events_fn(bigint) to agency_group;